### ISSUE TITLE
Import/Export FIG (Facility for Interactive Generation of figures files)

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#102]
Line drawing saved in the Xfig format; stored as a vector image that may include lines, shapes, arcs, splines, arrows, and text objects; may also include images, colors, and patterns.

Spec: http://mcj.sourceforge.net/fig-format.html
- parsing fig model v3.2
  - [x] color pseudo-object
  - [x] ellipse
  - [x] polyline
  - [x] spline
  - [x] text
  - [x] arc
  - [x] compound object
  - [x] arrow pseudo-object
  - [x] pic pseudo-object
- saving fig model v3.2
  - [x] color pseudo-object
  - [x] ellipse
  - [x] polyline
  - [x] spline
  - [x] text
  - [x] arc
  - [x] compound object
  - [x] arrow pseudo-object
  - [x] pic pseudo-object
- translator fig model to sK2 model
  - [x] layout (pages, metainfo)
  - [x] color pseudo-object
  - [x] ellipse
  - [x] polyline
  - [x] text
  - [x] arc
  - [x] compound object
  - [x] spline
  - [x] arrow pseudo-object
  - [x] pic pseudo-object
  -  styles
      - [x] shades fill color
      - [x] line style
      - [x] patterns fill
- translator sK2 model to fig model
  - [x] layout (pages, metainfo)
  - [x] layer  -> depth properties
  - [x] curve  -> to polyline
  - [x] rect  -> to polyline
  - [x] circle   ->  if possible to ellipse else to polyline
  - [x] polygon   -> to polyline
  - [x] text   -> to text
  - [x] group  -> ungroup
  - [x] pixmap
  - [ ] tpgroup
  -  styles
      - [ ] gradient fill
      - [x] line style
      - [x] patterns fill

| Features                                                                       | FIG | sK2  |
| :---                                                                                 | :---: |  :---:  |
| group objects on different layers                                  |   +   |   -    |
| arrows at the ends of  arcs                                           |   +   |   -    |
| multipage                                                                      |   -    |   +   |
| guide                                                                            |   -    |   +   |
| container                                                                      |   -    |   +   |
| gradient fill                                                                    |   -    |   +   |
| pattern fill set of background and foreground colors    |    -   |   +   |
| arbitrary angle of rotation bitmap                                 |   -    |   +   |
| compound paths (i.e., a path with multiple subpaths)  |    -   |   +   |

**Comment by sk1project** [comment]
@maxim-s-barabash Забыл сказать: сначала разобрать нужно на чанки, потом посторить FIG модель (так, чтобы SWord ее подхватывал) и только потом трансляторы в/из SK2

**Comment by maxim-s-barabash** [comment]
![screenshot_2018-06-12_01-29-53](https://user-images.githubusercontent.com/2724325/41260491-5336d504-6de0-11e8-9c2a-a7db5ff08143.png)

**Comment by maxim-s-barabash** [comment]
I close it. Feel free to open it again.
