### ISSUE TITLE
BUG : when changing the document page size it stays the same

### ISSUE THREAD

**Issue by unixino** [sk1project/sk1-wx#105]

**Comment by maxim-s-barabash** [comment]
Is this behavior of the new document file or open from a file?
Attach the log from the menu  Help / Log console

**Comment by sk1project** [comment]
Page size in Document properties dialog is a Default page size and will be applied for newly created page but not for existent pages. It's expected behavior but not a bug.

**Comment by unixino** [comment]
sorry about that

**Comment by sk1project** [comment]
@unixino you are doing a great job testing sk1! :)
