### ISSUE TITLE
sK1 build failure

### ISSUE THREAD

**Issue by Joermungand** [sk1project/sk1-wx#111]
Building sK1 (uc2 is fine) fails at line 132 in setup-sk1.py, `dirs = buildutils.get_dirs_tree('src/sk1/share')`. The definition of `get_dirs_tree` was removed from buildutils.py in commit [f496fdd0442642e86bce081ff26c75536e61a35c](https://github.com/sk1project/sk1-wx/commit/f496fdd0442642e86bce081ff26c75536e61a35c#diff-061bbb7899d848721374c8353a4aaf1c), yesterday.

As a workaround, I’ve replaced `buildutils.get_dirs_tree` with `buildutils.fsutils.get_dirs_tree` in setup-sk1.py, in the PKGBUILD on AUR, for now.

Thanks.

**Comment by sk1project** [comment]
Thank you for reported issue. Don't worry it's just an incomplete refactoring. Now it works correctly.
