### ISSUE TITLE
Outline arrows for unclosed curves

### ISSUE THREAD

**Issue by sk1project** [sk1project/sk1-wx#119]

**Comment by unixino** [comment]
Hi, I found a bug when converting stroke to curve, I converted it without the markers
![stroke bug](https://user-images.githubusercontent.com/37773191/40752345-a1712ce6-645e-11e8-841e-ab80bbead6a8.png)

**Comment by unixino** [comment]
Also there should be an option to change the markers size

**Comment by sk1project** [comment]
Yep, it's known issue. Just uncompleted implementation. Concerning marker size it should be a custom marker. But marker editing is a complex issue.

**Comment by sk1project** [comment]
@unixino arrow to curve issue is resolved. You could check it in master branch.
