### ISSUE TITLE
Nightly builds using OpenSUSE Build Service

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#12]
Please, setup OpenSUSE OBS for automatic nightly builds from fresh sources!
https://build.opensuse.org/

For example, there is is how OpenOrienteering project use it for its OOMapper application (cartographic DTP):
* https://github.com/openorienteering/mapper
* https://software.opensuse.org/download.html?project=home%3Adg0yt&package=openorienteering-mapper-unstable

**Comment by sk1project** [comment]
Now we have own build stack for SuSE distros.

**Comment by Symbian9** [comment]
> Now we have own build stack for SuSE distros.
 
@sk1project, and where is it? Where I can get nightly builds DEB's for Trusty?

**Comment by Symbian9** [comment]
http://downloads.sk1project.net/sk1/nightbuilds/
