### ISSUE TITLE
Importing PDF/EPS CMYK vectors?

### ISSUE THREAD

**Issue by unfa** [sk1project/sk1-wx#138]
I was wondering about using sK1 to process CMYK PDFs, however it seems that sK1 doens't import or export PDF files.

I know there's other software that does this, like Scribus - is it possible to make sK1 work with PDFs?

I am using Inkscape at work to process vector graphics (even for print!) but the fact that Inkscape doesn't work with CMYK is a problem. If I need to print something I export a n RGB PNG  fom Inkscape and convert it to CMYK TIFF with Krita.

**Comment by maxim-s-barabash** [comment]
Duplicate #9
