### ISSUE TITLE
Fix English text strings

### ISSUE THREAD

**Issue by coffee5** [sk1project/sk1-wx#142]
There are some grammatical and stylistic errors that should be fixed.

![36660751_2094986417439677_3559701068524814336_n](https://user-images.githubusercontent.com/41487898/43025163-5d6338c6-8c79-11e8-9102-d52889b2976a.png)
![36698225_2094984157439903_5623470521116000256_n](https://user-images.githubusercontent.com/41487898/43025164-5d89182a-8c79-11e8-8dae-2197986259de.png)

**Comment by maxim-s-barabash** [comment]
what kind of text you want to correct?
