### ISSUE TITLE
Uniconvertor: An error occurred: Parsing error: invalid character in hex string

### ISSUE THREAD

**Issue by lexterror** [sk1project/sk1-wx#145]
When trying to convert EPS to SVG I get the following error: 

An error occurred: Parsing error: invalid character in hex string

**Comment by lexterror** [comment]
Could I please try the 2.0 Nightly Windows Build to see if it works?

**Comment by sk1project** [comment]
@lexterror this is a known issue. Hope we will fix it in 2.0 version.
