### ISSUE TITLE
uc2 не открывает CDR последних версий.

### ISSUE THREAD

**Issue by Evgeniy-LOR** [sk1project/sk1-wx#146]
uc2 не конвертирует простые cdr to svg. 
Ошибка в консоли:
`ERROR  | Loader is not found for /tmp/magick-61106Uh76WnpCq7
ERROR  | Input file format of "/tmp/magick-61106Uh76WnpCq7" is unsupported.`
В логах uc2:
` INFO     | 10:57:38 AM | uc2.application --> Translation of "/tmp/magick-611tQnWKMZ89EIF" into "/tmp/magick-611cmCpwd8xl2A6.svg"
 INFO     | 10:57:38 AM | uc2.application --> Start to search saver by file extension svg
 INFO     | 10:57:38 AM | uc2.application --> Saver is found for extension svg
 INFO     | 10:57:38 AM | uc2.application --> Start to search for loader by file extension 
 WARNING  | 10:57:38 AM | uc2.application --> Loader is not found or not suitable for /tmp/magick-611tQnWKMZ89EIF
 INFO     | 10:57:38 AM | uc2.application --> Start to search loader by file content
 ERROR    | 10:57:38 AM | uc2.formats --> Error accessing <cdt> checker No module named cdt
 WARNING  | 10:57:38 AM | uc2.application --> By file content loader is not found for /tmp/magick-611tQnWKMZ89EIF
 INFO     | 10:57:38  ERROR    | 10:57:38 AM | uc2.application --> Loader is not found for test.cdr
 ERROR    | 10:57:38 AM | uc2.application --> Input file format of "test.cdr" is unsupported.
--> Input file format of "/tmp/magick-611tQnWKMZ89EIF" is unsupported.
`
[test_cdr.zip](https://github.com/sk1project/sk1-wx/files/2335198/test_cdr.zip) файлы для теста

**Comment by sk1project** [comment]
Спасибо за баг-репорт. CDR импортер еще пока не готов, поэтому неудивительно, что не открывает.
