### ISSUE TITLE
some issues on ubuntu 18.04

### ISSUE THREAD

**Issue by revast** [sk1project/sk1-wx#147]
- I cannot open a file by drag&drop onto the program
- I cannot open a file by issuing sk1 /path/to/file.svg and thus also not associate sk1 to svg files, because then the program gets open empty. 
- I cannot trace a raster file to vector - is there no conversion (e.g. via autotrace) (yet) built in?

otherwise, the program runs very smooth.

btw https://github.com/autotrace/autotrace seems to have activity again... It was removed from debian and consequently also from ubuntu... I still use (super-ancient) delineate autotrace gui for converting, at least there are sliders and some options (same as with gtk1 program frontline. but no palette selection - it gives some nice artistic twist if one is open for experimenting...). How do you guys trace your bitmaps? Inkscape's capabilities are somewhat questionable, but at least VectorMagic works fine with Wine...

**Comment by sk1project** [comment]
Thank you for proposed enhancements. We will implement them definitely!

**Comment by sk1project** [comment]
Concerning autotrace this lib is out of date and current tracing mainstream is potrace lib.

**Comment by revast** [comment]
yes, delineate just can use both. Sadly, there is no real current standalone GUI which tries to expose the features of protrace in an easy to use interface...

**Comment by maxim-s-barabash** [comment]
- https://github.com/sk1project/sk1-wx/commit/cd022e365d225a9e6c2bf467ce9b44953c32f633
- https://github.com/sk1project/sk1-wx/commit/8b2bc5c217852a6018245d377694ea39424e0c20
