### ISSUE TITLE
Cannot install on Xubuntu 18.10

### ISSUE THREAD

**Issue by Torsten-K** [sk1project/sk1-wx#152]
I cannot install/build sK1 on Xubuntu 18.10 (64 bit). There seems to be an issue with the Cairo library, and what the message says is that some files could not be found. But I have the newest version (libcairo2-dev). Here is the output from the terminal:

```
python setup-sk1.py build
running build
running build_py
running build_ext
building 'uc2.libcairo._libcairo' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-VlbVAf/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -IPackage -Ipycairo -Iwas -Inot -Ifound -Iin -Ithe -Ipkg-config -Isearch -Ipath.
Perhaps -Iyou -Ishould -Iadd -Idirectory -Icontaining -I`pycairo.pc'
to -IPKG_CONFIG_PATH -Ienvironment -Ivariable
No -Ipackage -I'pycairo' -I/usr/include/python2.7 -c src/uc2/libcairo/_libcairo.c -o build/temp.linux-x86_64-2.7/src/uc2/libcairo/_libcairo.o
src/uc2/libcairo/_libcairo.c:20:10: fatal error: pycairo.h: Datei oder Verzeichnis nicht gefunden
 #include <pycairo.h>
          ^~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
I have no idea what I could do, and I would be happy if someone could help me. Anyway, I experienced a couple of faults under Ubuntu 18.10. It seems like some crucial things have been changed under the hood, compared to version 18.04.

**Comment by sk1project** [comment]
Hi Torsten!

You just need installing pycairo-dev Take a look at the end of README file.
There we have described all dev dependencies for successful build. Also you
may download ready package for Ubuntu 18.10 from project website:
https://sk1project.net/viewpage.php?page_id=24

Regards,

Igor Novikov
https://sk1project.net

вс, 30 дек. 2018 г. в 03:11, Torsten Kelsch <notifications@github.com>:

**Comment by Torsten-K** [comment]
Thanks for your quick help, Igor.

I had tried to install the .deb package before, but it failed. I tried again today. There were some dependency problems with Python, which I had to fix. Also, I installed libmagickwand-6.q16. But still sK1 cannot be installed.

<pre>`The following packages have unfulfilled dependencies:
 python-sk1 : Depends on: libmagickwand-6.q16-3 but is not installable
E: Unfulfilled dependencies. Try "apt --fix-broken install" without specifying a package (or specify a solution).`</pre>

And:

<pre>`sudo apt install libmagickwand-6.q16-3
Packet lists are read... Ready
The dependency tree is created.       
Status information is read in.... Ready
Package libmagickwand-6.q16-3 is not available, but is supported by a different package
is referenced. This can mean that the package is missing, that it has replaced
or is only available from another source.

E: There is no installation candidate for package "libmagickwand-6.q16-3".

Translated with www.DeepL.com/Translator`</pre>

Anyway, this is a Ubuntu problem, not your fault, so I think I have to ask for help in the Ubuntu forums. I will report again after I have found a soiution (hopefully).

**Comment by sk1project** [comment]
wow, it seems we need updating dependencies for 18.10! This is our issue,
not Ubuntu.
Thank you for reported bug!

вс, 30 дек. 2018 г. в 15:02, Torsten Kelsch <notifications@github.com>:

**Comment by Torsten-K** [comment]
Thanks for your instant reply.

In the meantime, I upgraded to Ubuntu 19.04 (which is ALPHA, I know, I know), and libmagickwand-6.q16-6 has been installed as the latest version.

I hope the wonderful sK1 will run again on my machine after you have updated the dependencies. And thanks for all your efforts! Much appreciated!

**Comment by Torsten-K** [comment]
Now, when I try to install your nightly _build sk1-2.0rc4_20181231.tar.gz_, there is only one error left:

<pre>`src/uc2/libcairo/_libcairo.c:20:10: fatal error: pycairo.h: File or directory not found
 #include <pycairo.h>
          ^~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`</pre>

So, I think we are close to a final solution. It would really be great if I could work with your program again. What makes it stand out between similar software is that it enables perfect output for prepress. And this is exactly what I need. :-)

**Comment by sk1project** [comment]
The error log means absence of python-cairo-dev package. Please check here dependencies for successful build:

https://github.com/sk1project/sk1-wx#dependencies

Btw we have fixed Ubuntu 18.10 package dependencies. So you could try using it.

https://sk1project.net/viewpage.php?page_id=24

**Comment by Torsten-K** [comment]
Yes, you are right, the python-cairo-dev package was missing. I installed it, and everything works fine now. Thank you for your kind help and the very quick fix.

Can I make a small donation? I can’t find any PayPal button or something on your website. Apart from that, I will write a blog article about sK1 (unfortunately only in German language).

Best wishes for 2019!

**Comment by sk1project** [comment]
Thank you for proposition, but unfortunately we have no way to accept
donations.
The best way to help sK1 project is to promote application in web. So your
article will be great action!

Season's Greetings!

пн, 31 дек. 2018 г. в 21:54, Torsten Kelsch <notifications@github.com>:
