### ISSUE TITLE
Double header in Elementary OS

### ISSUE THREAD

**Issue by selwynorren** [sk1project/sk1-wx#156]
![screenshot from 2019-01-02 22-08-30](https://user-images.githubusercontent.com/570607/50610974-6feee800-0edd-11e9-980c-884d7ae6c191.png)
![screenshot from 2019-01-02 22-09-42](https://user-images.githubusercontent.com/570607/50610975-70877e80-0edd-11e9-8944-ef40931d9280.png)
As can be seen form the screenshots in Elementary OS, there is a weird additional header/Wrapper for SK1. if I have it in normal window mode, then there is a blank space with a shadow around it (which looks like the about screenshot)

**Comment by sk1project** [comment]
Thank you for reported issue!
It seems this is eOS specific bug in wxwidgets for interaction with eOS DE.
Unfortunately, we cannot fix it on application level. The problem can be
reproduced in small script:

import wxapp = wx.App(redirect=True)top = wx.Frame(None, title="Hello
World", size=(300,200))top.Show()app.MainLoop()


ср, 2 янв. 2019 г. в 22:27, Selwyn Orren <notifications@github.com>:

**Comment by sk1project** [comment]
wontfix

**Comment by selwynorren** [comment]
Thanks, I see if I run sk1 as GTK_CSD=0 sk1 then everything works just fine, however if I try and edit the .desktop file to show the same parameters, then it gives me an error saying I cannot use an = in teh first parameter of the script. Do you perhaps know of a work-around for that?

**Comment by selwynorren** [comment]
That's awesome. Thanks for your amazing work on SK1. I come form years of working in the pre-press industry and used to work exclusively with Freehand, I love what SK1 is shaping up to. Well Done!!

**Comment by sk1project** [comment]
@selwynorren we have fixed this issue. You can test latest build: https://sk1project.net/viewpage.php?page_id=24

**Comment by selwynorren** [comment]
absolutely perfect, thank you so much for this!!!
