### ISSUE TITLE
Cannot open or import CDR Format

### ISSUE THREAD

**Issue by selwynorren** [sk1project/sk1-wx#157]
I tried importing and opening a CDR-15 file. This does indeed open using Corel Draw. I am not sure if uniconverter is installed properly, herewith teh logs for the open attempt:

 INFO     | 12:21:08 AM | sk1.application --> Logging started
 INFO     | 12:21:08 AM | sk1.application --> Config is updated
 INFO     | 12:21:08 AM | sk1.application --> Application is initialized
 INFO     | 12:21:10 AM | sk1.application --> To start, create new document or open existing
 INFO     | 12:21:15 AM | sk1.application --> Start to search for loader by file extension cdr
 WARNING  | 12:21:15 AM | sk1.application --> Loader is not found or not suitable for /home/selwynorren/Documents/Work in Progress/Pixodigital/Clients/Centurion Furniture/Branding/Vehicle Door Vinyl.cdr
 INFO     | 12:21:15 AM | sk1.application --> Start to search loader by file content
 ERROR    | 12:21:15 AM | uc2.formats --> Error accessing <cdt> checker No module named cdt
 WARNING  | 12:21:17 AM | sk1.application --> By file content loader is not found for /home/XXXXXXXX/Documents/Work in Progress/Pixodigital/Clients/Centurion Furniture/Branding/Vehicle Door Vinyl.cdr
 INFO     | 12:21:17 AM | sk1.application --> Try using fallback loader
 ERROR    | 12:21:17 AM | sk1.application --> Loader is not found for /home/XXXXXXXX/Documents/Work in Progress/Pixodigital/Clients/Centurion Furniture/Branding/Vehicle Door Vinyl.cdr
 ERROR    | 12:21:18 AM | sk1.application --> Cannot open file </home/XXXXXXXX/Documents/Work in Progress/Pixodigital/Clients/Centurion Furniture/Branding/Vehicle Door Vinyl.cdr> Loader is not found for </home/XXXXXXXX/Documents/Work in Progress/Pixodigital/Clients/Centurion Furniture/Branding/Vehicle Door Vinyl.cdr>

**Comment by sk1project** [comment]
@selwynorren CDR importer is on initial implementation stage. So there is no sense to report issues about import.

**Comment by selwynorren** [comment]
Ahhh okay, so sorry I was not aware of that, Ill be patient - lol
