### ISSUE TITLE
UC2 SVG to PLT generates duplicate & tiny moves for large bitmap trace

### ISSUE THREAD

**Issue by lav8org** [sk1project/sk1-wx#158]
Using UC2 rc4 build 20190105 win64 headless

The input SVG is a traced bitmap of a circular Value ramp (gradient to polar coord) with 128 scans. 
The output has~170,000 moves where both x and y change <7 pixels, tiny relative to the max coord at ~23,000. Among these are ~129,000 duplicate points (x and y do not change). These are on more or less straight radial lines. The resulting file size is 44.3 MB. 
UC 1.1.5 doesn't have the same issue.
The Inkscape extension hpgl_encoder also doesn't have the issue; generates 11 tiny moves, 0 duplicates, and a file size of 1.28 MB

**Comment by sk1project** [comment]
@lav8org could you please providing a sample file?

**Comment by lav8org** [comment]
Yes, thanks for being quick and attentive. Thanks also for the excellent software; hpgl_encoder is terribly slow in comparison... for especially large files UC takes seconds or minutes while hpgl_encoder takes hours.
[helixstep1.1.svg.zip](https://github.com/sk1project/sk1-wx/files/2731111/helixstep1.1.svg.zip)
Upon taking a closer look the radial lines are actually extremely far from straight, contrary to my assumption... but relative to the other conversions and considering the number of duplicate points, the issue stands.

**Comment by sk1project** [comment]
@lav8org we have improved PLT optimization and added --plt_rounding_level parameter. Default value is 1, but if you set more this will remove additional points:
```
uniconvertor file.svg file.plt --plt_rounding_level=40
```
