### ISSUE TITLE
Keyboard shortcuts not working in text

### ISSUE THREAD

**Issue by olivierberten** [sk1project/sk1-wx#16]
Ctrl+letter within a text adds chars instead of performing actions (Ctrl+C, Ctrl+V, Ctrl+X, Ctrl+A, Ctrl+Z)

**Comment by maxim-s-barabash** [comment]
I have it working properly.

**Comment by sk1project** [comment]
Oliver, could you explain more details to reproduce this issue? It would be great to know distro version, desktop manager etc.

**Comment by olivierberten** [comment]
Ubuntu 16.04.1 LTS 64 bits
Gnome Shell 3.20.4-0ubuntu1~xenial2
Python 2.7.12
wxWidgets 3.0.2.0
UniConvertor 2.0
Cairo 1.14.6
pycairo 1.8.8
Pillow 3.1.2
LittleCMS 2.8
ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01
Pango 1.40.1
Reportlab 3.3.0

1. Create new file
2. Add some text
3. While editing the text, no macro is working: Ctrl+C, F10, Alt+F
F* do nothing
Alt+* do as if there was no Alt
Ctrl+letter insert uni0001 to uni001A for Ctrl+a to Ctrl+z
Ctrl+something else: as there was no Ctrl

**Comment by sk1project** [comment]
Great! Issue has been reproduced. Hope we will fix it before RC2.

**Comment by sk1project** [comment]
Fix is committed.
