### ISSUE TITLE
uc2.application --> Translation is interrupted maximum recursion depth exceeded

### ISSUE THREAD

**Issue by lav8org** [sk1project/sk1-wx#165]
Using latest nightly uniconvertor-2.0rc4-20190128-win64_headless. I've hit this with multiple files today. Possibly #96 bubbling up. I haven't been able to reproduce it with a file that I can make public.
[uc2.log](https://github.com/sk1project/sk1-wx/files/2801977/uc2.log)

**Comment by sk1project** [comment]
@lav8org we have fixed #96 and rebuilt binaries. You may check issue and close it if resolved.

**Comment by lav8org** [comment]
The trouble files passed! Thanks again for your excellent work.
