### ISSUE TITLE
UC2 headless SVG->PLT doesn't preserve layout

### ISSUE THREAD

**Issue by lav8org** [sk1project/sk1-wx#167]
All coordinates are translated by the smallest x,y values so that the minimum points are 0. This will override layout such as centering on the page. This might be intentional (hpgl_encoder does it too), but an option flag to disable and preserve user intention would be most welcome. If it makes it easier to code, even negative coordinates could be valid if someone chose to have their plotter origin centered on the page.
I expect a layout preserve flag would be a *bit* easier than implementing multiprocessing, which is otherwise easily done indirectly; I'm trying to speed up UC2s progress through SVGs with 35-100+ MB of path data by cloning the SVG into files with subsets of independent absolute paths, converting with separate UC2 instances, and joining back together. It would work if the paths weren't all getting pushed to (0,0).

**Comment by maxim-s-barabash** [comment]
@lav8org  are sure that the source SVG files have the correct coordinates? give a sample.

**Comment by lav8org** [comment]
@maxim-s-barabash Sure, here's an SVG of a square centered on an A4 page. The .PLT from UC2 is 

> `IN;PU0,5000;PD5000,5000;PD5000,0;PD0,0;PD0,5000;PU;`

[centeredsquare.zip](https://github.com/sk1project/sk1-wx/files/2816569/centeredsquare.zip)

**Comment by sk1project** [comment]
@lav8org try using `plt_force_zero=no` option for UC2. This will leave original coords. But you should be careful because negative values will not be restricted.

**Comment by lav8org** [comment]
@sk1project ah, very good, that will work! Centered origin is very logical, mathematicians approve *8-I
Are the UC2 options documented anywhere (other than the source)? I did a *brief* search before opening this thinking it might already be an option, but didn't find any beyond the --help.
Thanks again!!

**Comment by sk1project** [comment]
@lav8org The options are not documented yet because options support has been introduced in your issue #158 not so long ago,
