### ISSUE TITLE
SVG export unused namespaces and useless defaults

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#168]
unused namespaces

https://github.com/sk1project/sk1-wx/blob/b9b7c188711034b79727ca9694b7b9cc15c08a43/src/uc2/formats/svg/svg_const.py#L20-L23

useless defaults

https://github.com/sk1project/sk1-wx/blob/b9b7c188711034b79727ca9694b7b9cc15c08a43/src/uc2/formats/svg/svg_const.py#L25-L28

**Comment by sk1project** [comment]
@maxim-s-barabash fixed
