### ISSUE TITLE
SVG, add a unit for height and width attributes on root element

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#170]
A height, width  is a distance measurement, given as a number along with a unit.
in SVG-specific properties and their corresponding presentation attributes, the unit identifier is optional.

but  for correct determination of custom units it makes sense to set for the root element.

https://github.com/sk1project/sk1-wx/blob/8447d7559a3d939e9b59c613391d58430970e5b7/src/uc2/formats/svg/svg_translators.py#L1113-L1114

**Comment by sk1project** [comment]
It seems out of date reference. The issue has been fixed in master:
https://github.com/sk1project/sk1-wx/blob/13ee1cac76e856eb3367996e797f03f50cf9305b/src/uc2/formats/svg/svg_translators.py#L1131
