### ISSUE TITLE
dialog "gradient fill" is wrong

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#181]
body of dialog  a constant flicker, the widgets are not located in their places.

![Screenshot from 2019-03-17 23-55-55](https://user-images.githubusercontent.com/2724325/54498454-4821f480-4910-11e9-9ad2-59a551b95258.png)

**Comment by sk1project** [comment]
Please specify backend type (gtk2/gtk3) and platform (distro name)

**Comment by maxim-s-barabash** [comment]
Ubuntu 18.04
DE GNOME
wxWidgets 3.0.2.0 gtk3(classic)

**Comment by maxim-s-barabash** [comment]
It helped to remove all * .pyс files

**Comment by maxim-s-barabash** [comment]
https://github.com/sk1project/sk1-wx/commit/1316cba6444d56560ecb831788b84fb27ec95ba0
