### ISSUE TITLE
Mint 19 deb

### ISSUE THREAD

**Issue by AtsamazD** [sk1project/sk1-wx#193]
The guys, downloading the package for Mint 18, dpkg cursed unresolved dependency in Mint 19: libmagickwand-6.q16-2. I fixed the control on libmagickwand-6.q16-3 and rebuilt the package. May be useful.
https://drive.google.com/open?id=1L88zHhuyD6MJXEYXqV35qe2xHFy6kNBD

P.S. Сильно не пинать!)

**Comment by sk1project** [comment]
Which one package have you downloaded?
