### ISSUE TITLE
Windows64 and Windows32 builds are missing from webstite

### ISSUE THREAD

**Issue by zacharydonsky** [sk1project/sk1-wx#194]
The windows builds from your [downloads page](https://sk1project.net/modules.php?name=Products&product=sk1&op=download) are missing :(.

**Comment by sk1project** [comment]
Thank you for reported issue! We have fixed broken links.

**Comment by maxim-s-barabash** [comment]
for **uniconvertor** also need to be fixed

**Comment by sk1project** [comment]
fixed

**Comment by zacharydonsky** [comment]
Thanks very much!!
