### ISSUE TITLE
Spike: split sk1-wx on several subprojects

### ISSUE THREAD

**Issue by sk1project** [sk1project/sk1-wx#205]
It seems we need to simplify project structure and split it on following repos:

- sk1-wx
- uniconvertor
- sword
- wal
- build_utils
- build_cache

@maxim-s-barabash any ideas?

**Comment by maxim-s-barabash** [comment]
- i18n. Make Pot file for sk1 and uc2
- requirements.txt or requirements.in

**Comment by maxim-s-barabash** [comment]
Uc1 move to branch on uniconvertor

**Comment by sk1project** [comment]
- Label "spike" is about agile methodology. It means investigation.
- There is no sense to make requirement file because project requirements are described in README. Subproject dependencies are described in docs/depends.txt 
- UC 1.1.6 is in own branch
- Localization is a part of sk1-wx. There is no sense to provide localization for UC2 because of console nature of the application.
- setup.py is suitable for sk1-wx and uc2 only.
