### ISSUE TITLE
Can't make a direct link

### ISSUE THREAD

**Issue by mrkaban** [sk1project/sk1-wx#210]
Hello, I can’t get a direct link to download the program, I have a site with traffic of ~ 1000 people a day. I had to throw a disk on Yandex so that people could click download. Is there any way to simplify the process? For example, upload releases to github, or rss do (feedburner can help for free)?

Здравствуйте, не получается сделать прямую ссылку на загрузку программы, у меня сайт с посещаемостью ~ 1000 человек в день. Пришлось на яндекс диск закидывать, чтобы люди могли нажать скачать. Можно ли как-то упростить процесс? Например, загружать релизы на гитхаб, или  rss сделать (feedburner может помочь бесплатно)?

**Comment by sk1project** [comment]
Hi there! Try using direct browsing for https://downloads.sk1project.net 
Hope this helps resolving the issue.
