### ISSUE TITLE
Add "we-love-colors" plugin

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#222]
- https://github.com/fundevogel/we-love-colors

> This library provides an easy way to generate featuring the following (proprietary) color spaces:
> 
> - PANTONE®
> - RAL®
> - Dulux®
> - Copic®
> - Prismacolor®

### REFERENCE

- https://github.com/fundevogel/we-love-colors/issues/6
- http://forums.scribus.net/index.php/topic,3299.0.html

**Comment by maxim-s-barabash** [comment]
Hi! Users can import any palettes from the list of supported ones, .spk, .gpl, .xml, .soc, .cpl, .ase, .aco, .jcw. If additional palette file format is required, let us know.

**Comment by sk1project** [comment]
@Symbian9 I'm not sure that this code is legal and doesn't violate licenses of patent holders mentioned above. Github repo doesn't mean the code is legal.

**Comment by Symbian9** [comment]
> I'm not sure that this code is legal and doesn't violate licenses of patent holders mentioned above.

So, should I close this issue just now?
