### ISSUE TITLE
Update "sk1.pot" daily

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#229]
Currently, `sk1.pot` updated 8 month ago

- https://github.com/sk1project/sk1-wx/blob/master/po-sk1/sk1.pot

Need keep it fresh (automatically update it daily just before nightly build job started), so translators could use it immediately, without waiting for next 8 month.

**Comment by sk1project** [comment]
Translators may run locally `python setup.py update_pot` any time they wish.

**Comment by Symbian9** [comment]
> Translators may run locally `$ python setup.py update_pot` any time they wish.

Need add this info into `translation.md`:

- https://github.com/sk1project/sk1-wx/blob/master/docs/translation.md
