### ISSUE TITLE
UC2 PLT to PDF ValueError: too many values to unpack

### ISSUE THREAD

**Issue by lav8org** [sk1project/sk1-wx#233]
Checked with latest UC2 nightly (rc5-20190916-win64). Getting this error even for small number of commands. SVG to PDF where the SVG data is approximately the same as the plt works great.

[uc2.log](https://github.com/sk1project/sk1-wx/files/3623313/uc2.log)
[small.plt.txt](https://github.com/sk1project/sk1-wx/files/3623309/small.plt.txt)

**Comment by sk1project** [comment]
@lav8org we have reimplemented PLT format parsing. Now it supports the PLT file format that you have provided in this ticket.
