### ISSUE TITLE
Getting clang: error: linker command failed

### ISSUE THREAD

**Issue by Akash91** [sk1project/sk1-wx#236]
Trying to setup on 
mac 10.15 catalina
python2.7

> python setup.py build
running build
running build_py
running build_ext
building 'uc2.libpango._libpango' extension
clang -fno-strict-aliasing -fno-common -dynamic -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/pango/1.44.6/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.7/include/fribidi -I/usr/local/Cellar/harfbuzz/2.6.2/include/harfbuzz -I/usr/local/Cellar/graphite2/1.3.13/include -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/glib/2.62.1/include -I/usr/local/Cellar/glib/2.62.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.43/include -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/py2cairo/1.18.1/include/pycairo -I/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/uc2/libpango/_libpango.c -o build/temp.macosx-10.15-x86_64-2.7/src/uc2/libpango/_libpango.o
src/uc2/libpango/_libpango.c:546:8: warning: 'pango_find_base_dir' is deprecated [-Wdeprecated-declarations]
        dir = pango_find_base_dir(pango_layout_get_text(layout),-1);
              ^
/usr/local/Cellar/pango/1.44.6/include/pango-1.0/pango/pango-bidi-type.h:94:1: note: 'pango_find_base_dir' has been explicitly
      marked deprecated here
PANGO_DEPRECATED_IN_1_44
^
/usr/local/Cellar/pango/1.44.6/include/pango-1.0/pango/pango-version-macros.h:647:49: note: expanded from macro
      'PANGO_DEPRECATED_IN_1_44'
define PANGO_DEPRECATED_IN_1_44               PANGO_DEPRECATED
                                                ^
/usr/local/Cellar/pango/1.44.6/include/pango-1.0/pango/pango-version-macros.h:345:49: note: expanded from macro 'PANGO_DEPRECATED'
define PANGO_DEPRECATED                       G_DEPRECATED _PANGO_EXTERN
                                                ^
/usr/local/Cellar/glib/2.62.1/include/glib-2.0/glib/gmacros.h:942:37: note: expanded from macro 'G_DEPRECATED'
define G_DEPRECATED __attribute__((__deprecated__))
                                    ^
1 warning generated.
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.15-x86_64-2.7/src/uc2/libpango/_libpango.o -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lharfbuzz -lcairo -o build/lib.macosx-10.15-x86_64-2.7/uc2/libpango/_libpango.so
ld: library not found for -lintl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1

**Comment by sk1project** [comment]
Please note that you need compiling full dependencies stack before building the project. You can find dependencies here: https://github.com/sk1project/build-macos/tree/master/src

**Comment by Akash91** [comment]
Okay, let me check and get back
