### ISSUE TITLE
Rotating objects around rotation points...

### ISSUE THREAD

**Issue by dadoprom** [sk1project/sk1-wx#245]
If the rotation point (cross) is not in the center of the object (lets say it is in the left top corner), than the roatation is weird - see the attached video (in zip)...

[sk1-weird-rotation.zip](https://github.com/sk1project/sk1-wx/files/4014633/sk1-weird-rotation.zip)

**Comment by maxim-s-barabash** [comment]
preparing the patch
![rotate](https://user-images.githubusercontent.com/2724325/114278971-ea9efa00-9a3a-11eb-95e5-1ff007bd390c.gif)

**Comment by dadoprom** [comment]
YES YES YES, thank you :)
