### ISSUE TITLE
Can't install on Debian 10.x

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#246]
- **sK1:** `python-sk1-2.0rc5_20200108_debian_10_amd64.deb`
- **OS:** antiX 19.1 (Debian 10.x  buster)

Can't install prebuilt nightly DEB using GDebi

![pic.1](https://i.imgur.com/tYBCmTZ.png)

**Comment by sk1project** [comment]
Debian 10 deps have been fixed. Please try using latest night build  package and resolve this issue.
