### ISSUE TITLE
Snapping not work in "Edit mode"

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#247]
- **sK1:** `python-sk1-2.0rc5_20200115_debian_10_amd64.deb`
- **OS:** Debian 10.x

### Steps to reproduce

1. Launch sK1;
2. Create rectangle;
3. Enable all snap features;
4. Edit rectangle by moving edge to paper border (or any other object);

![pic.1](https://i.imgur.com/HfqxrGU.png)

### Actual behavior

Snapping not work in "Edit mode"

### Expected behavior

All snap features should work in "Edit mode" as expected.

**Comment by maxim-s-barabash** [comment]
![Peek 2021-04-20 21-34](https://user-images.githubusercontent.com/2724325/115447231-ea63e300-a220-11eb-96b5-ac55560b8df1.gif)
small update on the development process

**Comment by Symbian9** [comment]
> small update on the development process

Nice!
