### ISSUE TITLE
Packaging question: Arch Linux and python2-reportlab

### ISSUE THREAD

**Issue by Joermungand** [sk1project/sk1-wx#249]
Hi!

I maintain the Arch Linux build scripts in AUR for both sk1 and UC2. ReportLab is no longer available for Python 2 in Arch. They still compile on my system, as the package is still installed, but they will no longer build for new users. Am I to provide a PKGBUILD for Python 2 Reportlab?

**Comment by sk1project** [comment]
Hi! This would be great to support python2-reportlab because we have not ported applications on py3. We have started this task but 2.0 version will be released for py2 only.

**Comment by sk1project** [comment]
@Joermungand to support latest distros we have added `pycups` and `reportlab` into tarballs. So application build will install them locally using `pip` installer. The tarballs are selected specially to be compatible with python2.

**Comment by Joermungand** [comment]
I am maintaining AUR PKGBUILDs for both `python2-pycups` and `python2-reportlab`, so we’re covered for `pycups` and `reportlab` compatibility.
