### ISSUE TITLE
Add nightly builds for MX Linux MX-19.x

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#253]
### Actual behavior

*MX Linux* <= `MX-18.x`

- http://downloads.sk1project.net/sk1/nightbuilds/MX_Linux/

### Expected behavior

*MX Linux* <= `MX-19.x`

- https://distrowatch.com/table.php?distribution=mx&pkglist=true&version=19

**Comment by sk1project** [comment]
Fixed. Check build tonight.
