### ISSUE TITLE
Will there be a Python 3 version?

### ISSUE THREAD

**Issue by Torsten-K** [sk1project/sk1-wx#259]
As in Ubuntu 20.04 there is no more Python 2 support, my question is: Will there be a Python 3 version of SK1 in the near future?

**Comment by yurivict** [comment]
Same problem for the FreeBSD port, Python2 is discontinued and the port marked as deprecated:

```
DEPRECATED=	Uses deprecated version of python
EXPIRATION_DATE=	2020-08-15
```

**Comment by sk1project** [comment]
Hi all! Don't worry, py3 version is in progress already.

**Comment by someone-from-userland** [comment]
I kind of "bump" this since I found out that uniconvertor was pulled from Gentoo these days. (It's already masked and will be removed entirely probably soon.) That would be sad since it's sometimes hard to get a tool back into a distribution once it is gone.

**Comment by sk1project** [comment]
@someone-from-userland as we metioned above py2->py3 migration is in active process. Recentely we have implemented [SWord2](https://github.com/sk1project/sword2) application to support this migration because SWord2 allows introspecting document models and controling migration file formats one by one. [Previous version](https://github.com/sk1project/sword) has been outdated because works with python2 and Gtk2 only.
![Screenshot from 2020-07-05 12-47-07](https://user-images.githubusercontent.com/13432939/86530005-b1d76080-bebd-11ea-8bb4-d1783d442a87.png)

**Comment by VVD** [comment]
Hi!
Any news?

**Comment by sk1project** [comment]
Hi!
The porting is going on. We have ported all native bindings (lcms, cairo, pango, imagemagick) and continue porting step by step basic packages covering them by annotations, mock and functional tests.

**Comment by VVD** [comment]
Is py3 support done?

**Comment by sk1project** [comment]
@VVD still not. Py3 support is under active development.

**Comment by undrwater** [comment]
Is there somewhere to track development of the move to Py3?

**Comment by undrwater** [comment]
I found it, sorry. There is a Py3 branch in the git.

**Comment by maxim-s-barabash** [comment]
duplicates:  https://github.com/sk1project/sk1-wx/issues/176

**Comment by felipetesc** [comment]
Hi. I want to know the current status of sk1 porting to Python 3 and to say I can help. It would be nice to know what problems issues are you guys facing and how should I proceed. What modules arent ported, what was done and so on ..

**Comment by gabrielg81** [comment]
Is there somewhere to track development of the move to Py3?

**Comment by VVD** [comment]
@felipetesc, there is a branch https://github.com/sk1project/sk1-wx/tree/py3
You can fork project and try to work on this branch.
Or you can check other forks: https://github.com/sk1project/sk1-wx/network/members
Probably it's the best that somebody can do for project.

**Comment by VVD** [comment]
I see you already have fork: https://github.com/felipetesc/sk1-wx-py3
