### ISSUE TITLE
Straight Lines - Negative Translations

### ISSUE THREAD

**Issue by GeoHub2** [sk1project/sk1-wx#264]
Dear sk1-Team,

you are doing a great job.

Bugs I found in the "sk1 - vector graphics editor" (sk1-2.0rc5-20200912-win64-portable):

1) I don't get it how to draw a purely horizontal or vertical line. Right click doesn't offer to change the coordinates.

2) Transformations -> Position: doesn't allow negative entries.

Best regards
GeoHub2

**Comment by sk1project** [comment]
Hi @GeoHub2 

The features works under Linux. So we could suppose the same for win version. But we don't test it yet.

1.Select Polyline tool, click left mouse button to select start point. After that press CTRL button and move mouse. You will find that newly created line will be created under angle with 15 grad. step.

2.Select object. In Posion tab just entry negative value and press Apply button. This works in our test under Linux.
