### ISSUE TITLE
Please do not forget about this wonderful project

### ISSUE THREAD

**Issue by lobaluna** [sk1project/sk1-wx#265]
You have a great project. Do not forget about it. 
I am still waiting for the next Python 3.0 release. Yours SVG editor has features that makes it unique.

Congrats on all your generous job!

**Comment by sk1project** [comment]
@lobaluna don't worry! We are working for Python 3 migration. This is a complex issue because project code is a huge. But we resolve this task definitely!

**Comment by lobaluna** [comment]
Good fortune, and thanks for your great work!LobalunaEgo sum in porta limineEl 14 oct. 2020 4:36 a. m., sK1 Project <notifications@github.com> escribió:
@lobaluna don't worry! We are working for Python 3 migration. This is a complex issue because project code is a huge. But we will
resolve this task definitely!

**Comment by milosandjelkovic** [comment]
Will it be possible to run SK1 on distributions such as Ubuntu, after migration to Python 3? I can only run it on Debian-based distributions. By the way, great app.
