### ISSUE TITLE
Drawing a straight line with Polyline tool

### ISSUE THREAD

**Issue by uckermann** [sk1project/sk1-wx#27]
- [x] Maybe pressing "Crtl" or "Shitf" and use Polyline draw it in degrees, helping when need draw a straight line.
- [x] Editing Nodes too, help a lot move a nodes in straight line, with Ctrl or Shift pressed.

**Comment by maxim-s-barabash** [comment]
![Uploading Peek 2021-04-03 15-28.gif…]()
