### ISSUE TITLE
copy rectangle atribute 

### ISSUE THREAD

**Issue by budied** [sk1project/sk1-wx#271]
Hello SK1 team,

I found a little issue. When I try to copy stroke width value from one object to another object, the second object stroke value doesn't change automaticaly. the value change only if  make up/down the slide value. I am on Linux. 

Happy new year to all. 
 
Thank you.

--budied

**Comment by sk1project** [comment]
@budied Thank you for reported issue. The problem has been fixed. You can test it by fetching the latest build: 
https://sk1project.net/sk1/daily-builds/
