### ISSUE TITLE
resizing windows application

### ISSUE THREAD

**Issue by budied** [sk1project/sk1-wx#276]
Hello Sk1 Team, 

Thanks with stroke attribute issue response. Now it works with new daily build-20210130 version. But another issue come, when i try to resize the application window, the application retain its size. Tried another scenario by changed the desktop theme/DE, it still doesn't work too. Then backed to reinstall the old build-20210123, then the application window resize.  I'm in Linux.   

Thank you Sk1 Team.

**Comment by sk1project** [comment]
Hi @budied Could you send us an application preferences file? You can find it on path: `~/.config/sk1-wx/preferences.cfg`
We cannot reproduce the issue under Ubuntu 20.04 Hope you preferences file will help us to find the problem cause.

**Comment by budied** [comment]
Hi Sk1 Team,
here is the preferences. I installed on GeckoLinux based on openSuse. 
[preferences.txt](https://github.com/sk1project/sk1-wx/files/5900111/preferences.txt)

**Comment by sk1project** [comment]
@budied which DE are you using to reproduce the problem?

**Comment by budied** [comment]
Hi Sk1 Team, I use iceWM/XFCE/LxQT Gecko static 152. Actually if we try to resize the window left to right it is normal. The problem is when we try to resize down. So user cannot see the status bar, even the color bar. Seem the version-20210131, bigger than before. 
thank you.

**Comment by sk1project** [comment]
Such issue can be caused by window managers. For Ubuntu this problem is not reproduced. We will check this one on Gecko.

**Comment by budied** [comment]
thank you.

**Comment by sk1project** [comment]
We have tried GeckoLinux distro installed from:  GeckoLinux_STATIC_XFCE.x86_64-152.201210.0.iso
and sK1 package:  sk1-2.0rc5-0.20210203.opensuse15.0.x86_64.rpm

Main window resizing was as expected without described issues
![Screenshot-20210203210512-1337x981](https://user-images.githubusercontent.com/13432939/106798481-b2f48a00-6666-11eb-866d-2fc2a1a52c45.png)

**Comment by maxim-s-barabash** [comment]
FIXED: https://github.com/sk1project/sk1-wx/commit/8e64be5384f8d04592d804a57cbc79e825f8b842
