### ISSUE TITLE
Just an idea...Something to consider?

### ISSUE THREAD

**Issue by Correct-Syntax** [sk1project/sk1-wx#285]
In honesty, I am not sure how to present this as I will admit that I have not fully thought through all the rabbit-trails and problems this idea may bring. However, I think it has potential and hope you will consider it.

Basically, **I am wondering if the sk1 maintainers are apposed to a merge with a software program I and a few others have been working on** (read: experimenting with/planning/etc). 

The Original Project
=============

The software program is called Gimel Studio and the *original* Github repository is at https://github.com/Correct-Syntax/Gimel-Studio if you want to take a look. So, the goal with it was to create a node-based image editor. This was pretty successful, but based on feedback we knew that it could be far better with solid planning, goals and additional features, concepts, etc

Since then we decided that a rethinking and (somewhat of a) re-write of the application was needed to take it to the next level and make it a serious image editor.

The New Project (WIP)
==============

The current idea is to go in the direction of a 2D Sketch-like design tool+Image editor application where the normal editing is like you would expect from a vector editor (like sk1), but it also has node-based image editing, both for the images in the vector document and for post-design editing. 

This workflow basically allows for either vector or raster editing or both (though the raster image still is presented in the vector viewport in any case).

**The new repository is at https://github.com/GimelStudio/GimelStudio is you want to take a look there.**

Early WIP Mockup
============

**Obviously, it does not have to be exactly as I have it here**, but this is basically the latest mockup design I have come up with:

![Full HD](https://user-images.githubusercontent.com/60711001/113197436-49d66080-922a-11eb-9d58-c3899c872c26.jpg)

*Note: The vector viewport (center) doesn't have all of the tools, controls, etc for vector editing as I haven't gotten around to adding them to the mockup*

The vector objects are listed in the panel on the left and the "Layers" panel (top-left) is the list of "pages"/"artboards" or whatever we'd like to call them.

The node graph can be hidden at any time to save space and allow more space for the vector viewport.

Unfortunately, this mockup doesn't show everything (as mentioned above), but I hope it is enough to sorta show what I am thinking.

Why
===

- We won't have to re-implement all the vector stuff in Gimel Studio you all have already done and sk1 will benefit from extra raster support + UI improvements + wider user audience.
- The transition would be fairly straightforward as Gimel Studio also uses wxpython (so we're not switching UI toolkits or anything)
- At least some of the sk1 issues would be solved as they would be a part of the roadmap (e.g: #278 #150 #22 etc )

Also, if you would like, we could keep this idea as a separate thing from the current sk1 until you all were certain about it, etc.

Now, to You
========

Well, I hope I have presented everything okay. I just want to mention that in no way am I suggesting that sk1 is not a good software by itself, I just wanted to share my idea and see if we couldn't work together to make a better software program.

If you have questions or need more clarification on something, please just let me know. 

Please consider this idea and let me know your thoughts. I am hopeful that this can turn into something good. :)

Thank you for your time!

**Comment by maxim-s-barabash** [comment]
Thank you for your interest in the project. Unfortunately the project is going through a difficult time now.
But:
- For bitmaps we use magickwand. With an emphasis on support for the CMYK color space.
- sK1 uses WAL [Widgetset Abstraction Layer](https://github.com/sk1project/wal), not wx. Its meaning is that the widget is not used directly, but is used through an abstraction layer

**Comment by Correct-Syntax** [comment]
> Unfortunately the project is going through a difficult time now.

I was sorry to hear the news. My heartfelt condolences to you all. This was partly was caused me to have the idea -wanting to help the project as I seen that maintainers were/are needed.

> For bitmaps we use magickwand. With an emphasis on support for the CMYK color space.

I see. It seems that images are imported as RGB and can be converted to CMYK via ```Bitmaps > Convert to CMYK```. I can understand the emphasis on CMYK as that is better for print. I looks like your using uniconvertor also.

My thought was to use numpy + OpenImageIO + OpenColorIO for the core image stuff and GLSL shaders for on-GPU processing, etc. Also, possibly G'MIC if we would so desire.

> sK1 uses WAL Widgetset Abstraction Layer, not wx. Its meaning is that the widget is not used directly, but is used through an abstraction layer

I have looked into WAL (in the past and recently). It seems to be a collection of various utilities and custom widgets. From my experience with wxpython something like an abstraction layer really is needed for larger programs.

Anyway, I do see now that it would be quite difficult to make this happen -but I still do think it's a viable idea. :)

Thanks for considering.
