### ISSUE TITLE
Guides lock BUG

### ISSUE THREAD

**Issue by unixino** [sk1project/sk1-wx#293]
The area of a shape under a guide, There the guide can be moved even it's locked.

https://user-images.githubusercontent.com/37773191/114759466-7cba4180-9d5e-11eb-8fb5-102df2a9b1be.mp4

**Comment by maxim-s-barabash** [comment]
Delightfully. I'll see what I can do about it.

**Comment by maxim-s-barabash** [comment]
after the merge, it should go to nightly build.

**Comment by unixino** [comment]
Excellent, Thank you
