### ISSUE TITLE
Can't see nor edit nodes on an object in edit mode...

### ISSUE THREAD

**Issue by dadoprom** [sk1project/sk1-wx#295]
Can't see nor edit nodes on an object in edit mode...

See the attached file with the corrupted object...
[test.zip](https://github.com/sk1project/sk1-wx/files/6313498/test.zip)

This happened on the latest sk1 build...

**Comment by maxim-s-barabash** [comment]
As far as I know, "containers object" did not have edit nodes in edit mode.

**Comment by unixino** [comment]
This is weird, How can we change for example the size of a container that contains several objects ?
It is very difficult to ungroup all, Resizing the container then adding them again in the container.
Containers are widely used in brochure designs

**Comment by dadoprom** [comment]
Oh, I did not know this... so it is not a bug, sorry...

**Comment by maxim-s-barabash** [comment]
![Peek 2021-04-15 02-11](https://user-images.githubusercontent.com/2724325/114791912-fa4a7580-9d8f-11eb-8961-6de1215e7e82.gif)
this is a draft and testing is required.
what is your opinion on this?

**Comment by unixino** [comment]
YES That's the right behavior 
Than you for your hard work
I think the day that I can depend  only on SK1 without the help of other software is getting closer 
Thank you all

**Comment by maxim-s-barabash** [comment]
please give feedback on this change

**Comment by unixino** [comment]
As soon as I download the new version I will give feedback

**Comment by dadoprom** [comment]
Hi, I tested it, for now, it looks like it is working very good, if I notice something I will report it, thank you :)

**Comment by unixino** [comment]
It works great, Excellent work 
Thank you @maxim-s-barabash
