### ISSUE TITLE
Little enhancement to stroke and fill pop-up windows...

### ISSUE THREAD

**Issue by dadoprom** [sk1project/sk1-wx#298]
I think it would be nice to add an "Ok" button to stroke and fill pop-up windows...

and the behavior would be like this:
- when clicking on "Apply" the settings are applied but the window remains open
- when clicking on "Ok" the settings are applied and the window closes (this is what "Apply" does now)

Because I was editing a width of a line and did not know what width would be ok for what I was doing, so I changed it like 10x, and each time I had to reopen the stroke window for this...

![sk1_stroke_dialog](https://user-images.githubusercontent.com/19377506/115086592-d6f90500-9f0c-11eb-910c-e4ddbaa65386.png)

**Comment by unixino** [comment]
please take a look at #131

**Comment by dadoprom** [comment]
Yes, this looks awesome :) Thank you for your hard work!

**Comment by maxim-s-barabash** [comment]
Closed in favor of #131. if you want to continue just reopen this discussion.

**Comment by dadoprom** [comment]
How can I make the apply button just apply the change of color and do not close the pop-up window? I searched in the code, but I could not figure ouet how to do this change... thanx for your help :)

**Comment by Symbian9** [comment]
> How can I make the apply button just apply the change of color and do not close the pop-up window?

@dadoprom, Please, open new issue thread.
