### ISSUE TITLE
Page border shadow

### ISSUE THREAD

**Issue by unixino** [sk1project/sk1-wx#301]
Page border shadow is sometimes very annoying, So there should be an option to hide it .
![page border](https://user-images.githubusercontent.com/37773191/115475730-923cd900-a240-11eb-90ec-23d85780e525.jpg)

**Comment by maxim-s-barabash** [comment]
![Screenshot from 2021-04-21 11-22-03](https://user-images.githubusercontent.com/2724325/115521650-06549c80-a294-11eb-8b1d-486d9900966d.png)

I don't mind adding this option. but this change affects the document model. Hence the file format sk1. Also, the ui changes are temporarily frozen.

Alternatively, you can do this:

- Hide page border
- Set Desktop color

**Comment by unixino** [comment]
I see, No problem

**Comment by unixino** [comment]
I have an idea,
Why not using the page frame for that with little modifications  ?
1- make the frame on top of all layers and if all layers are hidden it stills be visible.
2- the frame must be locked ( can't move or edit it ).
3- changing the page size automatically changes the border size to the current page size.
4- the (page frame button) must be like (guides lock) button that means when enabled it shows the border and when disabled it hides the border.
5-the option ( show page frame ) will be disabled in document properties window, It only be enabled if ( show page border ) is disabled.
What do you think of that 
![20](https://user-images.githubusercontent.com/37773191/115601828-89024980-a2de-11eb-9000-ecc93b85bbed.jpg)

**Comment by maxim-s-barabash** [comment]
For this purpose there are guides around page

**Comment by unixino** [comment]
Yes but the page frame is another story.
But never mind, I will survive without it :)
We can consider this issue closed 
Thanks
