### ISSUE TITLE
Make the download links more prominent

### ISSUE THREAD

**Issue by da2x** [sk1project/sk1-wx#307]
I realize realize website is currently in a recovery state, but here are some website feedback originally provided on [Twitter](https://mobile.twitter.com/DaAleksandersen/status/1389778988680286213) while it was still functional:
> Hi, could you please make the download links more prominent on the project website? It took me five minutes to locate them. I expected to find a [big button-esque] download link [on [the product page](https://sk1project.net/sk1/)] between the first screenshot and the license information paragraph.
>
> I didn't even see the navigation menu floating off on the right-hand side. My brain dismissed it because of the low contrast. "Surely it couldn't possibly be important, right?" I then failed to notice the download link when I noticed [the menu] and scanned through the list.

**Comment by albertbronsky** [comment]
Thanks, I will look into this when I am done restoring the website.

**Comment by albertbronsky** [comment]
Easy to find download buttons have been added. 👍

<img width="689" alt="Screen Shot 2021-08-31 at 23 12 41" src="https://user-images.githubusercontent.com/44101337/131569607-39ceac37-1070-4bd0-a3f5-591199ea413e.png">
