### ISSUE TITLE
FR: Duplicate object with alt+drag

### ISSUE THREAD

**Issue by ryadhiprasetya** [sk1project/sk1-wx#311]
Add ability to copy or duplicate object with alt+drag key.

**Comment by maxim-s-barabash** [comment]
start moving. click on the right mouse button. release the right mouse button.

![Peek 2021-08-08 15-14](https://user-images.githubusercontent.com/2724325/128631637-6c94e4b4-8868-42a9-827e-0f3683fe4a99.gif)

**Comment by ryadhiprasetya** [comment]
wow. i don't know about that. thank you. this software is really great and meet industrial standard.

One question, how about array, or repeat duplicate with same direction

**Comment by maxim-s-barabash** [comment]
menu/arrange/transform/Position... (Alt+F5)

![Peek 2021-08-08 21-31](https://user-images.githubusercontent.com/2724325/128642149-fb4b2c68-ce3f-4ef4-9914-ea54df12b8c6.gif)
