### ISSUE TITLE
When you edit a spot color name, backspace moves the cursor to home

### ISSUE THREAD

**Issue by Magneticdud** [sk1project/sk1-wx#322]
Ubuntu, 2.0 rc 5 build 20210831

I created a new spot color, and named it rdgwhite. I wanted to add an underscore, like rdg_white, but backspace is moving the cursor on home. Not a big issue, but it's a little bit annoying

A quick snippet to see what I mean

https://user-images.githubusercontent.com/2940598/134920280-f95794c0-0d05-4565-aed6-e21b3f86bc05.mp4

**Comment by maxim-s-barabash** [comment]
Thanks. Confirm this behavior.

**Comment by maxim-s-barabash** [comment]
https://github.com/sk1project/wal/pull/2

**Comment by maxim-s-barabash** [comment]
@albertbronsky

**Comment by albertbronsky** [comment]
> @albertbronsky

Thanks, merged the fix. 
I have set up email forwarding from @sk1project account to mine for all Github pull requests to not miss any from now on. Sorry for the delay.
