### ISSUE TITLE
Rounded corners on rectangles are deformed if the aspect ratio is changed

### ISSUE THREAD

**Issue by Magneticdud** [sk1project/sk1-wx#323]
![immagine](https://user-images.githubusercontent.com/2940598/134921399-f72a46d5-a40c-4e59-8068-b554d400249e.png)

Sk1 2.0 rc5 build 20210831.

If you create an 1:1 square, then deform it with 1:5 ratio, then apply rounded corners, they are deformed.

They should be kept rounded.

This seems easy to understand for us humans, but in programming terms this might be tricky to fix, for example on CorelDRAW this problem was present until version X4, they took a decade to fix this

**Comment by maxim-s-barabash** [comment]
it's not a mistake. this is a feature :)

duplicate https://github.com/sk1project/sk1-wx/issues/277

**Comment by Magneticdud** [comment]
I searched and I could not find it - need to refine my searching skills :)

Nice to know that by modifying the size in edit mode you can have the best of the two worlds! (although i never found an occurrence where I needed the deformed corners ;) )
