### ISSUE TITLE
[ feature request ] multipage support in Sk1 project?

### ISSUE THREAD

**Issue by AlvesR0** [sk1project/sk1-wx#327]
If this is a duplicate. Sorry. Because I found nothing on the subject. Is there the possibility of implementing multi page in Sk1 project in a future version?

Greetings,
AlvesRO.

**Comment by aiamuzz** [comment]
I think it already has multipage support ... even i thought this may be a nice feature(mentioned the same in my other thread ... https://github.com/sk1project/sk1-wx/issues/325#issue-1022879434) but later found this feature already present in the software ...

**Comment by aiamuzz** [comment]
Please find the proof of this feature, however strangely there is no option(toolbar) to add pages, luckily i was able to invoke 'PageDown' option to get the add page window popup ... after the second page the 'right arrow' at the bottom footer of the app window lets you invoke the add page to the right

![image](https://user-images.githubusercontent.com/3283676/146055433-c601c5c9-d227-4146-a76c-51c0859ee723.png)

**Comment by maxim-s-barabash** [comment]
menu/Layout/Insert page...
