### ISSUE TITLE
Manjaro (Arch derivative) build

### ISSUE THREAD

**Issue by ssv-170379** [sk1project/sk1-wx#4]
Greetings, and sorry for bad English. I've succeded in compiling but had to change sources a bit. If the following changes are not ruining anything for other distros, I'd ask to include them to project.

First (according to http://reinout.vanrees.org/weblog/2013/09/24/pil-pillow-image-import.html )

**sk1-wx/src/uc2/formats/sk1/model.py** (line 19)
import Image -> **from PIL import Image**

and (just in case, I've got an error only with model.py file)

**sk1-wx/unit-tests/image_tests/__init__.py** (line 19)
import Image -> **from PIL import Image**

Second (according to http://www.wxpython.org/docs/api/wxversion-module.html )

**sk1-wx/src/script/sk1.tmpl** (somewhere at the beginning, let's say line 9, insert 2 new lines)
**import wxversion
wxversion.select("2.8")**

'coz by default Manjaro installs both wxgtk2.8 and 3.0 and treats 3.0 as a default one (via /usr/lib/python2.7/site-packages/wx.pth file), which also leads to error

Bye!

**Comment by sk1project** [comment]
We cannot using wxversion.select("2.8") because on MSW and OS X we need 3.0 only. So, we have fixed this issue in the application code to be compatible both 2.8 and 3.0 wx branches.

PIL import issues has been fixed.
