### ISSUE TITLE
Export or save formats

### ISSUE THREAD

**Issue by oxk4r01** [sk1project/sk1-wx#48]
Hi. I'm using Windows version. Is there possible to export or save in formats compatible with standard software, for example Illustrator, Corel, Inkscape? Can I save or export in *.svg format as well? Moreover, I think that copy in the clipboard in *.svg format, as programs such as Affinity Designer do, could be a great idea. This is a great software, but the saving and exporting formats it handles are very limitant in my opinion. 
Thanks in advance

**Comment by sk1project** [comment]
We have published RC2 (release candidate) snapshot. This development stage provides working editor but export/import functionality is scheduled for RC3 (current milestone). SVG support has been implemented. You could try it for Linux version: https://sk1project.net/viewpage.php?page_id=24
