### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rneto88** [sk1project/sk1-wx#49]
Hello, I found the project in a survey, I do some graphic work and I was very interested in the software. Would you like to know how to help translate it into Brazilian Portuguese?

-------------------------------------

Olá, encontrei o projeto numa pesquisa, faço alguns trabalhos gráficos e me interessei muito pelo software. Gostaria de saber como ajudar a traduzi-lo para português do Brasil?

**Comment by sk1project** [comment]
Now you could join to us as translator: https://www.facebook.com/308311182521658/photos/a.562085380477569.128234.308311182521658/1851228361563258/?type=3&theater&notif_t=page_post_reaction&notif_id=1522325951888404
