### ISSUE TITLE
Loosing dependencies

### ISSUE THREAD

**Issue by rsevero** [sk1project/sk1-wx#51]
I just tried to install _python-sk1-2.0rc2_0ubuntu1_16.10_amd64.deb_ on a 17.04 machine. 

It fails because _python-sk1-2.0rc2_0ubuntu1_16.10_amd64.deb_ depends on _libmagickwand-6.q16-**2**_ and 17.04 provides _libmagickwand-6.q16-**3**_.

Couldn't _python-sk1-2.0rc2_0ubuntu1_16.10_amd64.deb_ depend on _libmagickwand-6.q16_ instead of on _libmagickwand-6.q16-2_? This way it would be easier to use the provided packages.

**Comment by sk1project** [comment]
This is not wrong dependencies. Package for 16.10 is not suitable for 17.04. You could try using night build packages for 17.04: https://sk1project.net/viewpage.php?page_id=24
