### ISSUE TITLE
import SVG filter?

### ISSUE THREAD

**Issue by mspanish** [sk1project/sk1-wx#52]
Your editor looks very promising! Way faster than Inkscape 

Do you have an ETA for the SVG import?

Thanks for the hard work!

**Comment by sk1project** [comment]
SVG import/export have been implemented.
You could build application from source code or try using ready snapshot packages:
https://sk1project.net/viewpage.php?page_id=24

**Comment by mspanish** [comment]
yikes sorry but I'm on Windows - not sure how I'd do the build here!
