### ISSUE TITLE
uniconvertor not builded

### ISSUE THREAD

**Issue by tolyanor** [sk1project/sk1-wx#56]
I make commands:

git clone https://github.com/sk1project/sk1-wx uni-repo
cd uni-repo
sudo python setup-sk1.py install

and got error:
...
creating build/temp.linux-x86_64-2.7/src/uc2/libcairo
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -IPackage -Ipycairo -Iwas -Inot -Ifound -Iin -Ithe -Ipkg-config -Isearch -Ipath.
Perhaps -Iyou -Ishould -Iadd -Idirectory -Icontaining -I`pycairo.pc'
to -IPKG_CONFIG_PATH -Ienvironment -Ivariable
No -Ipackage -I'pycairo' -I/usr/include/python2.7 -c src/uc2/libcairo/_libcairo.c -o build/temp.linux-x86_64-2.7/src/uc2/libcairo/_libcairo.o
src/uc2/libcairo/_libcairo.c:20:21: fatal error: pycairo.h: Нет такого файла или каталога
 #include <pycairo.h>

**Comment by sk1project** [comment]
Before compilation you should install devel packages described in README.txt
