### ISSUE TITLE
sK1 build fails

### ISSUE THREAD

**Issue by Joermungand** [sk1project/sk1-wx#63]
Hi,

I maintain the sK1 and UC2 nightly PKGBUILDs on AUR.

Ever since commit e2471b5 yesterday, sK1 fails to build. This appears to be caused by importing appconst from module sk1 in setup-sk1.py (the entire module is initialised, as well as all imports recursively until _cms is reached, which at this point has not been compiled and is not available). In the PKGBUILD, I have temporarily solved this by copying appconst to the root of the source tree and replacing `from sk1 import appconst`  with `import appconst` in setup-sk1.py.

Thanks,

Alex

**Comment by sk1project** [comment]
We will fix it today definitely.

**Comment by sk1project** [comment]
The issue has been fixed.

**Comment by Joermungand** [comment]
Works like a charm. Thanks a lot!
