### ISSUE TITLE
src/uc2/libimg/_libimg.c:20:29: fatal error: wand/MagickWand.h: No such file or directory

### ISSUE THREAD

**Issue by l29ah** [sk1project/sk1-wx#67]
Tried to build master, and it tries to include a nonexistant file. In /usr/include/ImageMagick-7/ i see MagickWand/MagickWand.h, but simple name substitution produces more errors.

**Comment by Joermungand** [comment]
SK1 needs ImageMagick 6 (only libmagick 6, actually). If that is installed on your system, you need to tell it where to look for it. In Arch, it is done by setting the PKG_CONFIG_PATH variable. Take a look at the build() section in the build script for Arch available here: [https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sk1-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sk1-git).

**Comment by l29ah** [comment]
Same problem except the path ends in 6 now with 6.9.9.33. Also the oldest imagemagick available in Gentoo is 6.9.9.23.

**Comment by Joermungand** [comment]
It 6.9.9.33 should work; in Arch it’s at 6.9.9.34 and sK1 builds just fine. Have you checked the actual PKG_CONFIG path on your system? It might not be the same in Gentoo as it is in Arch. The behaviour you have described is exactly the same as I experienced before setting the path correctly.

**Comment by sk1project** [comment]
Duplicates https://github.com/sk1project/sk1-wx/issues/69
