### ISSUE TITLE
Import Image file

### ISSUE THREAD

**Issue by selwynorren** [sk1project/sk1-wx#68]
Hi,

I am running SK! on Solus OS and it works really well. However I cannot seem to import PNG or JPG files. Is there something I should be installing?

**Comment by Joermungand** [comment]
It looks the the issue we had in Arch when ImageMagick got updated to version 7. SK1 only works with 6. What version of ImageMagic do you have in Solus?

**Comment by selwynorren** [comment]
Hello, Yes your 100% correct Solus is on v7

**Comment by Joermungand** [comment]
Well, then you need to see if they also have v6 in their repositories (libmagickwand or equivalent + dev libraries if Solus uses them; they should have v6, a number of other apps, such as Inkscape, depend on it) and recompile SK1 against it. In Arch this is easily achieved by setting the appropriate variable before building:
`export PKG_CONFIG_PATH="/usr/lib/imagemagick6/pkgconfig"`
But the actual path may differ on Solus.

**Comment by selwynorren** [comment]
Okay makes sense to me. Solus only come with v7.07 and I am unsure of a way to install v6. Interestingly, I installed inkscape after reading your post and it works with image importing using v7. Will SK1 update accordingly in the future?

**Comment by Joermungand** [comment]
I’ve absolutely no idea of how Solus works, but I’ve just downloaded their latest Inkscape package and I cannot find anything related to ImageMagick in the dependencies (might still be covered indirectly), although it looks like it’s the same version as in Arch.
As for SK1, I wouldn’t know, either. That’s one question only the developer can answer. I only maintain the build scripts in AUR. Sorry.

**Comment by selwynorren** [comment]
Thanks Joermungand for your advise. I cant wait to use SK1. I have been a long time user of Macromedia Freehand. and do not like teh new alternatives. SK1 seems to be truly the only viable alternative

**Comment by Joermungand** [comment]
You’re welcome. I, too, think SK1 looks very promising.

**Comment by sk1project** [comment]
Duplicates https://github.com/sk1project/sk1-wx/issues/69
