### ISSUE TITLE
Support Imagemagick 7

### ISSUE THREAD

**Issue by samuelcecilio** [sk1project/sk1-wx#69]
Hi, I'm trying to build sk1 and uniconvertor 2.0 on Solus, which uses ImageMagick 7 (I assume they have no plans to include version 6 in the repos). But I get the following error:

`src/uc2/libimg/_libimg.c:20:10: fatal error: wand/MagickWand.h: No such file or directory`

I also read that:

> It looks like they rearranged the location of header files in ImageMagick-7.x:
>
> https://github.com/ImageMagick/ImageMagick/blob/master/MagickWand/MagickWand.h
> https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/MagickCore.h
>
> Assuming the bindings are still compatible with the newest ImageMagick, once the headers are found, > you could try creating symlinks in your install location:
>
> magick -> MagickCore
> wand -> MagickWand
>
> https://github.com/gographics/imagick/issues/86

**Comment by sk1project** [comment]
[This feature has been implemented.](https://www.facebook.com/308311182521658/photos/a.562085380477569.128234.308311182521658/1836708609681900/)
