### ISSUE TITLE
Incorrect SVG import - shapes and groups scattered after import

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#70]
SVG file:

- https://gist.github.com/Symbian9/d1ef82d8ad09377efc76a92ad03b63ce

This SVG in *Inkscape* `0.92.1 r15371`
![Inkscape SVG](http://pasteall.org/pic/show.php?id=130630)

This SVG in *sK1* `2.0rc3_20180228`
![sK1 SVG scattered](http://pasteall.org/pic/show.php?id=130629)

OS: MXLinux MX-17 (Debian 9 "Stretch")

Platform: x86_64 (amd64)

**Comment by sk1project** [comment]
@Symbian9 fixed
