### ISSUE TITLE
Add guide for translators

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#72]
Add "TRANSLATING.md" instruction for help translators understand how to localize *sK1 2.0*

- [ ] https://github.com/sk1project/sk1-wx/blob/master/TRANSLATING.md

![sK1 Translators](http://i.imgur.com/l4dJhPH.png)

### REFERENCE

- https://github.com/OpenOrienteering/mapper/wiki/Translation

**Comment by sk1project** [comment]
https://github.com/sk1project/sk1-wx/blob/master/docs/translation.md
