### ISSUE TITLE
image placed inside container

### ISSUE THREAD

**Issue by selwynorren** [sk1project/sk1-wx#81]
Hi, After placing an image inside a container, if I try and resize the container the image inside also resizes. Is the a way to unbind these two so I can resize the container without resizing the contents.

Also it would be great to reposition the container content by holding down the alt key to something similar?

**Comment by sk1project** [comment]
To resize container only you need extract container content by `Arrange -> Extract from container`
Of course, container functionality could be improved and we are going to do that.
