### ISSUE TITLE
move nodes in orthographic mode and create strait lines by using Shift key (production ready)

### ISSUE THREAD

**Issue by unixino** [sk1project/sk1-wx#82]

**Comment by sk1project** [comment]
"create strait lines by using Shift key (production ready)" this issue has been resolved

**Comment by unixino** [comment]
No it didn't i cant move nodes in orthographic directions

**Comment by maxim-s-barabash** [comment]
I confirm. when editing nodes, modifier Shift, CTRL, ALT keys are used

**Comment by sk1project** [comment]
@unixino @maxim-s-barabash  As for me subj has twо parts:
* move nodes in orthographic mode
* create strait lines 
Last issue has been resolved in polyline creator. If you mean something else please add detailed description.

**Comment by unixino** [comment]
yes in polyline i can draw strait lines in x and y directions using ( CTRL ) but the movement of the mouse cursore when drawing in strait lines should be locked to move only in ( x , y ) directions and 45 angles .
The same thing should be when moving node(s) .

**Comment by sk1project** [comment]
Never saw cursor locking. Neither Inkscape nor CorelDraw lock cursor. Did you see such effect somewhere?

**Comment by unixino** [comment]
YES in illustrator when you draw with SHIFT key the cursor jumps in these directions only, I see that this is the best behavior

**Comment by sk1project** [comment]
In which Illustrator version? There is no such behavior for Illustrator 8.

**Comment by unixino** [comment]
![ezgift](https://user-images.githubusercontent.com/37773191/59205132-7ecf7a00-8ba2-11e9-9daa-2e331003ff89.gif)

**Comment by sk1project** [comment]
As I see the cursor is not locked on your animation. Application locks possible line continuation but not cursor. The same we have implemented.

**Comment by unixino** [comment]
What i mean is that the cursor jumps in these angles only like a magnet, That dosent happend in SK1
I will show you

**Comment by unixino** [comment]
![sk](https://user-images.githubusercontent.com/37773191/59206068-6fe9c700-8ba4-11e9-9c8d-81c30b492759.gif)
This was recorded using CTRL key and i still can move the cursore in all directions and even i can still draw in non orthographic directions

**Comment by maxim-s-barabash** [comment]
curve_fixed_angle
I understood the problem.
Hot-keys when creating a curve \ poliline in sK1.

Ctrl -  Limits the stirring curve to (option curve_fixed_angle) by default 15 degrees.
Shift - Temporarily disables the restriction entered Ctrl

**Comment by unixino** [comment]
I see, Then the default degrees should be 45 not 15

**Comment by maxim-s-barabash** [comment]
@unixino, need an icon for the menu item "Edit" :)
https://github.com/sk1project/sk1-wx/pull/204

**Comment by unixino** [comment]
Thanks, a Very good solution.
The icons are for tools only  ;) :)

**Comment by unixino** [comment]
Hi
There is a bug in the polyline tool when starting from existing line the first node doesn't snap i must add node then the snap works 
![polylinebug](https://user-images.githubusercontent.com/37773191/113158316-fb31c200-923b-11eb-90f2-e98ef99b4397.gif)

Also still can't move nodes with snapping using the mouse, to move a node in X or Y directions i must use keyboard.


https://user-images.githubusercontent.com/37773191/113159128-a773a880-923c-11eb-9151-a939109c4231.mp4

@maxim-s-barabash

**Comment by maxim-s-barabash** [comment]
@unixino, the first will be fixed after the patch is accepted #286. 

the second will be implemented in another issues https://github.com/sk1project/sk1-wx/issues/27

**Comment by unixino** [comment]
Thanks
