### ISSUE TITLE
Fix issues in Ukrainian locales

### ISSUE THREAD

**Issue by sk1project** [sk1project/sk1-wx#84]
Dear translators @Symbian9 @maxim-s-barabash, please find common solution for the locale.

**Comment by maxim-s-barabash** [comment]
just in case you don't know  https://github.com/sk1project/sk1-wx/commit/cc13f1f30552f46b66ec68edc092d67c541adc7a#comments

**Comment by sk1project** [comment]
I would propose to create branch #84 and resolve these issues there.

**Comment by Symbian9** [comment]
> У технічному перекладі логічно казати "виберіть потрібні файли", "виберіть кодування цієї сторінки", "виберіть адресата(ів)". До речі, майже завжди коли мова йде про вибір кількох елементів - слово "оберіть" стає недоречно пафосним.

Там питання не лише до "виберіть" але і до "позначте" - взагалі ці слова досить неоднозначні .

> "виберіть потрібні файли"

В данному випадку "виберіть" дуже схоже за змістом "вийміть" ("виберіть усю картоплю з лунки"). Тобто іде вказівка на завершену дію, а от "оберіть" тут якраз означає проміжну дію ("оберіть потрібне, а потім будемо з обраним щось робити"). Обравши необхідні файли ми потім вирішуємо - відкривати чи імпортувати їх (потрібна дія підтвердження заверешення операії)

>  "виберіть кодування цієї сторінки"

"встановіть кодування цієї сторінки"

> "виберіть адресата(ів)"

"вкажіть адресата(ів)"

> А коли обираємо щось одне й хоч трохи надовго - воно влучає саме в ціль. "Оберіть теку встановлення", "Оберіть типове кодування", "Оберіть безпеку та зручність нашого продукту!".

А от якщо щось кудись потрібно зберегти чи експортувати то потрібно не "оберати", а саме "вказувати" (бо це наказ)

**Comment by Symbian9** [comment]
Щодо "позначити" -- тут я більше схиляюся до "виділити", бо "позначити" означає залишити якусь позначку (відмітку) на чомусь.

Всі операції пов'язані з виіделенням одного або більше об'єктів для подальшоі обробки потрібно називати "виділенням об'єктів", а не "позначенням об'єктів"

**Comment by maxim-s-barabash** [comment]
Щоб не впадати в полеміку можна подивитися на досвід інших проектів, наприклад:
libreoffice: https://github.com/LibreOffice/translations/tree/master/source/uk
inkscape: https://gitlab.com/inkscape/inkscape/tree/master/po

**Comment by sk1project** [comment]
Народ, бренча для фиксов: https://github.com/sk1project/sk1-wx/tree/issue-84
Если нет опыта с бренчами - спрашивайте. Если все ок - пушить в issue-84
На дальнейшее - все изменения в коде должны иметь тикет и соотв. ветку issue-<номер тикета>
По завершению - пулл реквест ветки в мастер.

**Comment by Symbian9** [comment]
Що LibreOffice, що Inkscape - перекладаются виключно волонтерами (так як і sK1)

І я б не сказав що українські переклади (локалі) в цих програмах (так як і у інших вільних проектах) є ідеалами для наслідування та не містять помилок.

Рекомендую зазирнути в історію коммітів з українським перекладом LibreOffice та Inkscape -- за остнані кілька років лексика там змінилася і в багатьох випадках не відповідає нормам словників Інституту української мови НАН України.

**Comment by Symbian9** [comment]
> Text on Path Group

Як правильно (суть)?

- група "текстів на контурах"
- текст на "групі контурів"

**Comment by Symbian9** [comment]
>  Если все ок - пушить в issue-84

@sk1project, НЕ працює - відкриваю для редагування...

- https://github.com/sk1project/sk1-wx/edit/issue-84/po-sk1/uk.po

... а кнопка <key>Commit changes</key> не активна (не можу натиснути).

**Comment by Symbian9** [comment]
@maxim-s-barabash, ось робоча версія `uk.po` у вигляді gist'у

- https://gist.github.com/Symbian9/1da2b61f90a314fccfadc1f0516449ea#file-uk-po

Виправив відповідно до твоїх коментарів і дещо інше підправив та прибрав подвійні пробіли між словами

P.S.: У мене щось чи з мережею, чи з браузером - не виходить комміти в репозитаріях публікувати через сайт вчора і сьогодні... :-/

**Comment by sk1project** [comment]
@Symbian9 для правки через веб-интерфейс сначала надо сделать изменения, а потом и кнопка активируется :) Не забываем комментировать коммиты (хотя бы кратко типа "uk translation fix") - НЛО в хистори не нужны. Не нужно в деталях описывать изменения перевода, достаточно инфы, что это фиксы перевода.

**Comment by sk1project** [comment]
@Symbian9 постараюсь сделать мануал для разрабов, чтобы объяснить как работать локально, а не в вебе.

**Comment by Symbian9** [comment]
> для правки через веб-интерфейс сначала надо сделать изменения, а потом и кнопка активируется :)

@sk1project, та ні, це таки Github щось начудив зі сторінкою редактора коду на сайті і тепер через веб-браузер (Pale Moon) неможливо вносити коміти онлайн %-)

- https://github.com/MoonchildProductions/Pale-Moon/issues/1662#issuecomment-378529581

> постараюсь сделать мануал для разрабов, чтобы объяснить как работать локально, а не в вебе.

+1.

**Comment by maxim-s-barabash** [comment]
У першому варіанті я спирався на переклад inkscape.
Потребує уточнення: 
Fill - Заповнення -> заливка
Stroke - Штрихи -> обведення

**Comment by Symbian9** [comment]
> Fill - Заповнення -> заливка

Швидше "Заповнення", бо буває "Заповнення візерунком" і "Заповнення заливкою" (однотонне заповнення)

> Stroke - Штрихи -> обведення

Я за "Контур" (контур рисунку; контурний рисунок - рисунок на якому відсутні/прозорі заповнення, як в книжках-розмальовках). "Обведення" - це щось ближче до "зовнішній контур".

"Штрихи" часто використовують в українських локалях різних графічних редакторів, але саме в українській мові цей термін більше зі "штриховкою" (заповнення штриховкою на кресленнях) асоціюєтся.

P.S.: Треба буде ще поритися у словниках щодо "Stroke" і "Fill"
