### ISSUE TITLE
Remove *.mo files from git

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#85]
these files can be created by building

**Comment by sk1project** [comment]
Not for MSW build. It's not a good idea to maintain MO tools under windows.

**Comment by maxim-s-barabash** [comment]
but if convert .po to .mo using https://pypi.org/project/polib/

**Comment by maxim-s-barabash** [comment]
Bump

**Comment by sk1project** [comment]
@maxim-s-barabash fixed
