### ISSUE TITLE
Tab Document Properties Details

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#93]
The summary statistics of all the properties of the document.
The list of properties needs to be clarified.

![details](https://user-images.githubusercontent.com/2724325/38452774-a1eca9aa-3a53-11e8-884a-ec7665a749d4.png)

- [x] implement this

**Comment by sk1project** [comment]
@maxim-s-barabash не нужно делать таб, т.к. в неанглийских локалях там уже места для новых табов нет. Лучше собранные данные вывести в отдельный диалог, привязанный к кнопке "Statistics"
![38452774-a1eca9aa-3a53-11e8-884a-ec7665a749d4](https://user-images.githubusercontent.com/13432939/38471801-ddcaeea6-3b7e-11e8-82c9-e9749acfc9db.png)

**Comment by sk1project** [comment]
Под фичу отдельную бренчу. Мастер теперь протектед и без кодревьюв в него нельзя пушить и мерджить.

**Comment by maxim-s-barabash** [comment]
![screenshot from 2018-04-12 08-23-08](https://user-images.githubusercontent.com/2724325/38657839-fe6643e6-3e2a-11e8-9831-ba960e62b5b6.png)
