### ISSUE TITLE
Replace pages with art boards and a proposal for Artboards Widget

### ISSUE THREAD

**Issue by unixino** [sk1project/sk1-wx#98]
art boards is more flexible than pages it is better an easier to work with than pages because you can see and compare multiple designs at once.
![art boardwidget-15-15](https://user-images.githubusercontent.com/37773191/40274206-321f5b98-5bc0-11e8-90e9-bb75b1b48b95.jpg)

**Comment by sk1project** [comment]
Artboards are not suitable for sK1 because they breaks document architecture.
